// Code generated by protoc-gen-go. DO NOT EDIT.
// source: yumaddressbook.proto

/*
Package yumaddressbook is a generated protocol buffer package.

It is generated from these files:
	yumaddressbook.proto

It has these top-level messages:
	PersonRequest
	PersonReply
	PeopleReply
*/
package yumaddressbook

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the user's id.
type PersonRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *PersonRequest) Reset()                    { *m = PersonRequest{} }
func (m *PersonRequest) String() string            { return proto.CompactTextString(m) }
func (*PersonRequest) ProtoMessage()               {}
func (*PersonRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PersonRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// The request message containing the user's id.
type PersonReply struct {
	Id        string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Firstname string `protobuf:"bytes,2,opt,name=firstname" json:"firstname,omitempty"`
	Lastname  string `protobuf:"bytes,3,opt,name=lastname" json:"lastname,omitempty"`
	Address   string `protobuf:"bytes,4,opt,name=address" json:"address,omitempty"`
}

func (m *PersonReply) Reset()                    { *m = PersonReply{} }
func (m *PersonReply) String() string            { return proto.CompactTextString(m) }
func (*PersonReply) ProtoMessage()               {}
func (*PersonReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PersonReply) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PersonReply) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *PersonReply) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

func (m *PersonReply) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

// The response message containing the list of persons
type PeopleReply struct {
	People []*PersonReply `protobuf:"bytes,1,rep,name=people" json:"people,omitempty"`
}

func (m *PeopleReply) Reset()                    { *m = PeopleReply{} }
func (m *PeopleReply) String() string            { return proto.CompactTextString(m) }
func (*PeopleReply) ProtoMessage()               {}
func (*PeopleReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PeopleReply) GetPeople() []*PersonReply {
	if m != nil {
		return m.People
	}
	return nil
}

func init() {
	proto.RegisterType((*PersonRequest)(nil), "yumaddressbook.PersonRequest")
	proto.RegisterType((*PersonReply)(nil), "yumaddressbook.PersonReply")
	proto.RegisterType((*PeopleReply)(nil), "yumaddressbook.PeopleReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for AddrBookRestAPI service

type AddrBookRestAPIClient interface {
	// Gets a person details
	GetPerson(ctx context.Context, in *PersonRequest, opts ...grpc.CallOption) (*PersonReply, error)
}

type addrBookRestAPIClient struct {
	cc *grpc.ClientConn
}

func NewAddrBookRestAPIClient(cc *grpc.ClientConn) AddrBookRestAPIClient {
	return &addrBookRestAPIClient{cc}
}

func (c *addrBookRestAPIClient) GetPerson(ctx context.Context, in *PersonRequest, opts ...grpc.CallOption) (*PersonReply, error) {
	out := new(PersonReply)
	err := grpc.Invoke(ctx, "/yumaddressbook.AddrBookRestAPI/GetPerson", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AddrBookRestAPI service

type AddrBookRestAPIServer interface {
	// Gets a person details
	GetPerson(context.Context, *PersonRequest) (*PersonReply, error)
}

func RegisterAddrBookRestAPIServer(s *grpc.Server, srv AddrBookRestAPIServer) {
	s.RegisterService(&_AddrBookRestAPI_serviceDesc, srv)
}

func _AddrBookRestAPI_GetPerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PersonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddrBookRestAPIServer).GetPerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/yumaddressbook.AddrBookRestAPI/GetPerson",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddrBookRestAPIServer).GetPerson(ctx, req.(*PersonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AddrBookRestAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "yumaddressbook.AddrBookRestAPI",
	HandlerType: (*AddrBookRestAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPerson",
			Handler:    _AddrBookRestAPI_GetPerson_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "yumaddressbook.proto",
}

func init() { proto.RegisterFile("yumaddressbook.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 243 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0xcf, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0x6d, 0x27, 0xd3, 0xbe, 0xe1, 0x84, 0x28, 0x12, 0xa6, 0xe2, 0xe8, 0x69, 0xa7, 0x0a,
	0xdb, 0x5f, 0xd0, 0x5e, 0x64, 0xb7, 0x90, 0x9b, 0xe0, 0xa5, 0x33, 0x4f, 0x09, 0x6b, 0xf7, 0xb2,
	0x24, 0x3d, 0xec, 0xbf, 0x97, 0xa6, 0x9d, 0x3f, 0x0a, 0xee, 0xf8, 0xfd, 0x41, 0x3e, 0x2f, 0x5f,
	0xb8, 0x3d, 0x34, 0x75, 0xa9, 0x94, 0x45, 0xe7, 0x36, 0x44, 0xdb, 0xcc, 0x58, 0xf2, 0xc4, 0xa6,
	0x7f, 0xdd, 0xf4, 0x09, 0xae, 0x04, 0x5a, 0x47, 0x3b, 0x89, 0xfb, 0x06, 0x9d, 0x67, 0x53, 0x88,
	0xb5, 0xe2, 0xd1, 0x3c, 0x5a, 0x24, 0x32, 0xd6, 0x2a, 0xdd, 0xc3, 0xe4, 0x58, 0x30, 0xd5, 0x61,
	0x18, 0xb3, 0x07, 0x48, 0x3e, 0xb4, 0x75, 0x7e, 0x57, 0xd6, 0xc8, 0xe3, 0x60, 0xff, 0x18, 0x6c,
	0x06, 0x97, 0x55, 0xd9, 0x87, 0xa3, 0x10, 0x7e, 0x6b, 0xc6, 0xe1, 0xa2, 0x3f, 0x84, 0x9f, 0x87,
	0xe8, 0x28, 0xd3, 0xa2, 0x45, 0x92, 0xa9, 0xb0, 0x43, 0xae, 0x60, 0x6c, 0x82, 0xe4, 0xd1, 0x7c,
	0xb4, 0x98, 0x2c, 0xef, 0xb3, 0xc1, 0xcf, 0x7e, 0xdd, 0x27, 0xfb, 0xea, 0xf2, 0x0d, 0xae, 0x73,
	0xa5, 0x6c, 0x41, 0xb4, 0x95, 0xe8, 0x7c, 0x2e, 0xd6, 0x6c, 0x0d, 0xc9, 0x0b, 0xfa, 0xae, 0xcc,
	0x1e, 0xff, 0x7b, 0x24, 0xac, 0x30, 0x3b, 0xc5, 0x48, 0xcf, 0x8a, 0x67, 0xb8, 0xd3, 0x94, 0x7d,
	0x5a, 0xf3, 0x3e, 0xe8, 0x15, 0x37, 0xaf, 0x4d, 0x9d, 0x77, 0xba, 0x65, 0x8b, 0x76, 0x74, 0x11,
	0x6d, 0xc6, 0x61, 0xfd, 0xd5, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x48, 0x80, 0xfe, 0xdb, 0x95,
	0x01, 0x00, 0x00,
}
