// Code generated by protoc-gen-go. DO NOT EDIT.
// source: addrbookrestapi.proto

/*
Package addrbookrestapi is a generated protocol buffer package.

It is generated from these files:
	addrbookrestapi.proto

It has these top-level messages:
	PersonRequest
	PersonReply
	PeopleReply
*/
package addrbookrestapi

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the user's id.
type PersonRequest struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *PersonRequest) Reset()                    { *m = PersonRequest{} }
func (m *PersonRequest) String() string            { return proto.CompactTextString(m) }
func (*PersonRequest) ProtoMessage()               {}
func (*PersonRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PersonRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// The request message containing the user's id.
type PersonReply struct {
	Id        int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Firstname string `protobuf:"bytes,2,opt,name=firstname" json:"firstname,omitempty"`
	Lastname  string `protobuf:"bytes,3,opt,name=lastname" json:"lastname,omitempty"`
	Email     string `protobuf:"bytes,4,opt,name=email" json:"email,omitempty"`
	Phoneno   string `protobuf:"bytes,5,opt,name=phoneno" json:"phoneno,omitempty"`
}

func (m *PersonReply) Reset()                    { *m = PersonReply{} }
func (m *PersonReply) String() string            { return proto.CompactTextString(m) }
func (*PersonReply) ProtoMessage()               {}
func (*PersonReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PersonReply) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PersonReply) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *PersonReply) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

func (m *PersonReply) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *PersonReply) GetPhoneno() string {
	if m != nil {
		return m.Phoneno
	}
	return ""
}

// The response message containing the list of persons
type PeopleReply struct {
	People []*PersonReply `protobuf:"bytes,1,rep,name=people" json:"people,omitempty"`
}

func (m *PeopleReply) Reset()                    { *m = PeopleReply{} }
func (m *PeopleReply) String() string            { return proto.CompactTextString(m) }
func (*PeopleReply) ProtoMessage()               {}
func (*PeopleReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PeopleReply) GetPeople() []*PersonReply {
	if m != nil {
		return m.People
	}
	return nil
}

func init() {
	proto.RegisterType((*PersonRequest)(nil), "addrbookrestapi.PersonRequest")
	proto.RegisterType((*PersonReply)(nil), "addrbookrestapi.PersonReply")
	proto.RegisterType((*PeopleReply)(nil), "addrbookrestapi.PeopleReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for AddrBookRestAPI service

type AddrBookRestAPIClient interface {
	// Gets a person details
	GetPerson(ctx context.Context, in *PersonRequest, opts ...grpc.CallOption) (*PersonReply, error)
	// Creates a person details
	PostPerson(ctx context.Context, in *PersonReply, opts ...grpc.CallOption) (*PersonReply, error)
	// Updates a person details
	PutPerson(ctx context.Context, in *PersonReply, opts ...grpc.CallOption) (*PersonReply, error)
}

type addrBookRestAPIClient struct {
	cc *grpc.ClientConn
}

func NewAddrBookRestAPIClient(cc *grpc.ClientConn) AddrBookRestAPIClient {
	return &addrBookRestAPIClient{cc}
}

func (c *addrBookRestAPIClient) GetPerson(ctx context.Context, in *PersonRequest, opts ...grpc.CallOption) (*PersonReply, error) {
	out := new(PersonReply)
	err := grpc.Invoke(ctx, "/addrbookrestapi.AddrBookRestAPI/GetPerson", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addrBookRestAPIClient) PostPerson(ctx context.Context, in *PersonReply, opts ...grpc.CallOption) (*PersonReply, error) {
	out := new(PersonReply)
	err := grpc.Invoke(ctx, "/addrbookrestapi.AddrBookRestAPI/PostPerson", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addrBookRestAPIClient) PutPerson(ctx context.Context, in *PersonReply, opts ...grpc.CallOption) (*PersonReply, error) {
	out := new(PersonReply)
	err := grpc.Invoke(ctx, "/addrbookrestapi.AddrBookRestAPI/PutPerson", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AddrBookRestAPI service

type AddrBookRestAPIServer interface {
	// Gets a person details
	GetPerson(context.Context, *PersonRequest) (*PersonReply, error)
	// Creates a person details
	PostPerson(context.Context, *PersonReply) (*PersonReply, error)
	// Updates a person details
	PutPerson(context.Context, *PersonReply) (*PersonReply, error)
}

func RegisterAddrBookRestAPIServer(s *grpc.Server, srv AddrBookRestAPIServer) {
	s.RegisterService(&_AddrBookRestAPI_serviceDesc, srv)
}

func _AddrBookRestAPI_GetPerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PersonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddrBookRestAPIServer).GetPerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/addrbookrestapi.AddrBookRestAPI/GetPerson",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddrBookRestAPIServer).GetPerson(ctx, req.(*PersonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddrBookRestAPI_PostPerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PersonReply)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddrBookRestAPIServer).PostPerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/addrbookrestapi.AddrBookRestAPI/PostPerson",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddrBookRestAPIServer).PostPerson(ctx, req.(*PersonReply))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddrBookRestAPI_PutPerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PersonReply)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddrBookRestAPIServer).PutPerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/addrbookrestapi.AddrBookRestAPI/PutPerson",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddrBookRestAPIServer).PutPerson(ctx, req.(*PersonReply))
	}
	return interceptor(ctx, in, info, handler)
}

var _AddrBookRestAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "addrbookrestapi.AddrBookRestAPI",
	HandlerType: (*AddrBookRestAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPerson",
			Handler:    _AddrBookRestAPI_GetPerson_Handler,
		},
		{
			MethodName: "PostPerson",
			Handler:    _AddrBookRestAPI_PostPerson_Handler,
		},
		{
			MethodName: "PutPerson",
			Handler:    _AddrBookRestAPI_PutPerson_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "addrbookrestapi.proto",
}

func init() { proto.RegisterFile("addrbookrestapi.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 279 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0x41, 0x4e, 0xc3, 0x30,
	0x10, 0x45, 0x71, 0x43, 0x0b, 0x99, 0x0a, 0x2a, 0x59, 0x45, 0x58, 0x55, 0x05, 0x51, 0x56, 0x59,
	0x45, 0xa2, 0x70, 0x81, 0x86, 0x05, 0x2a, 0x6c, 0xac, 0xdc, 0x20, 0xc5, 0x06, 0xac, 0xa6, 0x19,
	0x63, 0xbb, 0x0b, 0x4e, 0xc0, 0x89, 0xd9, 0xa3, 0x3a, 0x0d, 0x20, 0x4b, 0x94, 0x0d, 0xcb, 0x3f,
	0xff, 0xe9, 0xfb, 0x7b, 0x34, 0x70, 0x56, 0x09, 0x61, 0x96, 0x88, 0x2b, 0x23, 0xad, 0xab, 0xb4,
	0xca, 0xb5, 0x41, 0x87, 0x74, 0x14, 0x8c, 0xd3, 0x4b, 0x38, 0xe1, 0xd2, 0x58, 0x6c, 0x4a, 0xf9,
	0xba, 0x91, 0xd6, 0xd1, 0x53, 0xe8, 0x29, 0xc1, 0x48, 0x42, 0xb2, 0xa8, 0xec, 0x29, 0x91, 0xbe,
	0x13, 0x18, 0x76, 0x84, 0xae, 0xdf, 0x42, 0x9f, 0x4e, 0x21, 0x7e, 0x52, 0xc6, 0xba, 0xa6, 0x5a,
	0x4b, 0xd6, 0x4b, 0x48, 0x16, 0x97, 0xdf, 0x03, 0x3a, 0x81, 0xe3, 0xba, 0xda, 0x99, 0x91, 0x37,
	0xbf, 0x34, 0x1d, 0x43, 0x5f, 0xae, 0x2b, 0x55, 0xb3, 0x43, 0x6f, 0xb4, 0x82, 0x32, 0x38, 0xd2,
	0x2f, 0xd8, 0xc8, 0x06, 0x59, 0xdf, 0xcf, 0x3b, 0x99, 0xde, 0x6e, 0x8b, 0xa0, 0xae, 0x65, 0x5b,
	0xe4, 0x06, 0x06, 0xda, 0x4b, 0x46, 0x92, 0x28, 0x1b, 0xce, 0xa6, 0x79, 0xf8, 0xe5, 0x1f, 0xb5,
	0xcb, 0x1d, 0x3b, 0xfb, 0x20, 0x30, 0x9a, 0x0b, 0x61, 0x0a, 0xc4, 0x55, 0x29, 0xad, 0x9b, 0xf3,
	0x05, 0x7d, 0x80, 0xf8, 0x4e, 0xba, 0x96, 0xa6, 0x17, 0xbf, 0xc6, 0xf8, 0xfd, 0x4c, 0xf6, 0x3e,
	0x93, 0x1e, 0xd0, 0x7b, 0x00, 0x8e, 0xb6, 0x4b, 0xdb, 0x4b, 0xff, 0x99, 0xb5, 0x80, 0x98, 0x6f,
	0xfe, 0x25, 0xaa, 0xb8, 0x82, 0x73, 0x85, 0xf9, 0xb3, 0xd1, 0x8f, 0x21, 0x58, 0x8c, 0x83, 0x7d,
	0xf0, 0xed, 0xa5, 0x70, 0xb2, 0x1c, 0xf8, 0x93, 0xb9, 0xfe, 0x0c, 0x00, 0x00, 0xff, 0xff, 0xbf,
	0x72, 0x50, 0xfd, 0x4b, 0x02, 0x00, 0x00,
}
